// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuaoyhHpJzXyv-MrnKpu1_X93OOrnmUUI',
    appId: '1:319354946505:web:1b1167d0997f37e49f1e18',
    messagingSenderId: '319354946505',
    projectId: 'vnvc-notification',
    authDomain: 'vnvc-notification.firebaseapp.com',
    storageBucket: 'vnvc-notification.appspot.com',
    measurementId: 'G-ZVLWMXXRCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtoupba7no5wWzcNW5_uZ4Rk-AKFUwEug',
    appId: '1:319354946505:android:26c2e3ed5113c9d39f1e18',
    messagingSenderId: '319354946505',
    projectId: 'vnvc-notification',
    storageBucket: 'vnvc-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrUvqRA6V4mtcfIW_uIy9DgtABsWJliA',
    appId: '1:319354946505:ios:832ad1dcdecded089f1e18',
    messagingSenderId: '319354946505',
    projectId: 'vnvc-notification',
    storageBucket: 'vnvc-notification.appspot.com',
    iosClientId: '319354946505-vrfiq3u49hnlloiifgu0v72ca3a5ktsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfrUvqRA6V4mtcfIW_uIy9DgtABsWJliA',
    appId: '1:319354946505:ios:832ad1dcdecded089f1e18',
    messagingSenderId: '319354946505',
    projectId: 'vnvc-notification',
    storageBucket: 'vnvc-notification.appspot.com',
    iosClientId: '319354946505-vrfiq3u49hnlloiifgu0v72ca3a5ktsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
